events {
    worker_connections 1024; # Maximum number of connections per process
}

http {
    
    upstream iris-apis {
        server mlops-iris-api:8000;
    }

    # Defining our http server
    server {
        listen 80;
        # Domain name or IP that this server block manages
        server_name localhost;
        # Redirect all HTTP requests to HTTPs
        return 301 https://$host$request_uri;
    }
    # Defining new HTTPs server
    server {
        listen 443 ssl; # enable ssl
        server_name localhost;

        # Paths to SSL certificates inside nginx container
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        # SSL protocols and ciphers
        ssl_protocols TLSv1.2 TLSv1.3; # only allow modern versions of TLS
        ssl_ciphers HIGH:!aNULL:!MD5; # list of allowed cipher suits
        ssl_prefer_server_ciphers on; # prefer server ciphers
    
        # All requests that start with /predict/ will be handled here
        location /predict {
            # Add authentication
            auth_basic "API Access Protected"; # message
            auth_basic_user_file /etc/nginx/.htpasswd; # path to .htpasswd file in container
            proxy_pass http://iris-apis;
            # proxy_pass: Redirects the request to the backend service
            # http://iris-api:8000 : 'iris-api' is the name of our API service.
            #8000 is the internal port the API listens on.

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            allow 172.18.0.0/16;
            deny all;
        }
    }
    
}